[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
src.branch = "master"
fetch.github = "vim-jp/vimdoc-ja"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
src.branch = "main"
fetch.github = "vim-skk/skkeleton"

[cmp-skkeleton]
src.git = "https://github.com/uga-rosa/cmp-skkeleton"
src.branch = "main"
fetch.github = "uga-rosa/cmp-skkeleton"

[mini-bufremove]
src.git = "https://github.com/echasnovski/mini.bufremove"
src.branch = "main"
fetch.github = "echasnovski/mini.bufremove"

[hlchunk-nvim]
src.github = "shellRaining/hlchunk.nvim"
src.prefix = "v"
fetch.url = "https://github.com/shellRaining/hlchunk.nvim/archive/refs/tags/v$ver.tar.gz"

[ts-error-translator-nvim]
src.github = "dmmulroy/ts-error-translator.nvim"
src.prefix = "v"
fetch.url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v$ver.tar.gz"

[tailwind-tools-nvim]
src.github = "luckasRanarison/tailwind-tools.nvim"
src.prefix = "v"
fetch.url = "https://github.com/luckasRanarison/tailwind-tools.nvim/archive/refs/tags/v$ver.tar.gz"

[noice-nvim]
src.github = "folke/noice.nvim"
src.prefix = "v"
fetch.url = "https://github.com/folke/noice.nvim/archive/refs/tags/v$ver.tar.gz"
