# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  conform-nvim = {
    pname = "conform-nvim";
    version = "619363c30309d29ffa631e67c8183f2a72caa373";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "619363c30309d29ffa631e67c8183f2a72caa373";
      fetchSubmodules = false;
      sha256 = "sha256-pMWvC7sqOFjsMUhxTzMcoSifn7E5CVindvQVl9dEfB8=";
    };
    date = "2026-05-24";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "760912b5992e1d6437378a9c7f2b0cb950966cf5";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "760912b5992e1d6437378a9c7f2b0cb950966cf5";
      fetchSubmodules = false;
      sha256 = "sha256-xmGMDVfypiJ8y4LJ0zGYsClVkjyuNH8B9U5XEeE0bN4=";
    };
    date = "2026-06-30";
  };
  gitlinker-nvim = {
    pname = "gitlinker-nvim";
    version = "5.5.0";
    src = fetchurl {
      url = "https://github.com/linrongbin16/gitlinker.nvim/archive/refs/tags/v5.5.0.tar.gz";
      sha256 = "sha256-UVCVLZT9VdgiwFSQFFIf7wEaMUZGsIJjikJpxjuL97g=";
    };
  };
  herdr-splits-nvim = {
    pname = "herdr-splits-nvim";
    version = "0926e8c375deeee19a0317a051a9ed43ca16e76c";
    src = fetchFromGitHub {
      owner = "lmilojevicc";
      repo = "herdr-splits.nvim";
      rev = "0926e8c375deeee19a0317a051a9ed43ca16e76c";
      fetchSubmodules = false;
      sha256 = "sha256-gogvi3a4Tzv1SHuOch+wFRYmbouexRHhX6uTXnqUWOg=";
    };
    date = "2026-07-02";
  };
  hlchunk-nvim = {
    pname = "hlchunk-nvim";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/shellRaining/hlchunk.nvim/archive/refs/tags/v1.3.0.tar.gz";
      sha256 = "sha256-eYwifigTRrXrW6xpFqLlqYFAftt64yweRGvvAvE7o5U=";
    };
  };
  noice-nvim = {
    pname = "noice-nvim";
    version = "4.10.0";
    src = fetchurl {
      url = "https://github.com/folke/noice.nvim/archive/refs/tags/v4.10.0.tar.gz";
      sha256 = "sha256-L9VGtlqsAezmi45ElHEmUFKCnrNQh8BA0ao9MJoyRr8=";
    };
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "2.10.0";
    src = fetchurl {
      url = "https://github.com/neovim/nvim-lspconfig/archive/refs/tags/v2.10.0.tar.gz";
      sha256 = "sha256-IEmmnlGVUEefdylHO0u7fshr1XNCGR4vGQ9+QXioC7o=";
    };
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "2.31.0";
    src = fetchurl {
      url = "https://github.com/folke/snacks.nvim/archive/refs/tags/v2.31.0.tar.gz";
      sha256 = "sha256-TW5yI7AFU1AxNcZ2bzBMnH1txhGbClDvBGmsMg0wNJw=";
    };
  };
  ts-error-translator-nvim = {
    pname = "ts-error-translator-nvim";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v2.0.1.tar.gz";
      sha256 = "sha256-SSLrY2+0shDy/gvZeFmMGlLEZdtbMQT7XBS0WvF8X98=";
    };
  };
  vim-stylus = {
    pname = "vim-stylus";
    version = "99031823d216c4433fb5c2661a33a43fbebaff61";
    src = fetchFromGitHub {
      owner = "wavded";
      repo = "vim-stylus";
      rev = "99031823d216c4433fb5c2661a33a43fbebaff61";
      fetchSubmodules = false;
      sha256 = "sha256-tIVBNAAj78jJnoaejs850L+b4aTfp/UDFQQCxauAAcw=";
    };
    date = "2023-02-03";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "c8c3b339302b4e88be2859b3ba99a4f0a3a2f8bd";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "c8c3b339302b4e88be2859b3ba99a4f0a3a2f8bd";
      fetchSubmodules = false;
      sha256 = "sha256-362QsKxCbqXrOru3p+ReoqtfwTLSSblNGzzxTE2DWoI=";
    };
    date = "2026-06-27";
  };
}
