# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cmp-skkeleton = {
    pname = "cmp-skkeleton";
    version = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "cmp-skkeleton";
      rev = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
      fetchSubmodules = false;
      sha256 = "sha256-Odg0cmLML2L4YVcrMt7Lrie1BAl7aNEq6xqJN3/JhZs=";
    };
    date = "2023-11-26";
  };
  hlchunk-nvim = {
    pname = "hlchunk-nvim";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/shellRaining/hlchunk.nvim/archive/refs/tags/v1.3.0.tar.gz";
      sha256 = "sha256-eYwifigTRrXrW6xpFqLlqYFAftt64yweRGvvAvE7o5U=";
    };
  };
  mini-bufremove = {
    pname = "mini-bufremove";
    version = "1ee294a97e091d3cf967974df622c0d887890dc2";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.bufremove";
      rev = "1ee294a97e091d3cf967974df622c0d887890dc2";
      fetchSubmodules = false;
      sha256 = "sha256-tYE7ib/F3emDxHaeEW/k/P31/gKknLsw63H9T5yAEEo=";
    };
    date = "2024-07-01";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "882ec0c10856aadd0c2bf843b9b04cf16272a19b";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "882ec0c10856aadd0c2bf843b9b04cf16272a19b";
      fetchSubmodules = false;
      sha256 = "sha256-b3tDU4iz0tV3mebSPlmvXDSrvw8hdR5w0EPyDXjaiqA=";
    };
    date = "2024-09-03";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "1fa7e5b4f332aec82d70db4524f80be3be45e992";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "1fa7e5b4f332aec82d70db4524f80be3be45e992";
      fetchSubmodules = false;
      sha256 = "sha256-aUZp/FjZSUeHa6L1cJdOC4pzvrNV3AiqXumLVZLEoig=";
    };
    date = "2024-09-03";
  };
}
