# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  conform-nvim = {
    pname = "conform-nvim";
    version = "016802de402556da54c36bd7359b441266b01cdd";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "016802de402556da54c36bd7359b441266b01cdd";
      fetchSubmodules = false;
      sha256 = "sha256-7VkQLpkDak/O5tphT/EWX/rE9r0Dd2UCF5CFbl4rK+A=";
    };
    date = "2026-08-11";
  };
  copilot-language-server-darwin-arm64 = {
    pname = "copilot-language-server-darwin-arm64";
    version = "1.547.0";
    src = fetchurl {
      url = "https://github.com/github/copilot-language-server-release/releases/download/1.547.0/copilot-language-server-darwin-arm64-1.547.0.zip";
      sha256 = "sha256-ZgHa2/aGUFsoACyZ8paCEf2P0an+ct2IQQOy702cSno=";
    };
  };
  copilot-language-server-darwin-x64 = {
    pname = "copilot-language-server-darwin-x64";
    version = "1.547.0";
    src = fetchurl {
      url = "https://github.com/github/copilot-language-server-release/releases/download/1.547.0/copilot-language-server-darwin-x64-1.547.0.zip";
      sha256 = "sha256-+gkvqRJ6aQLHYL78C0CtI2H81sXGqpKaDzYMhFLyCSw=";
    };
  };
  copilot-language-server-linux-arm64 = {
    pname = "copilot-language-server-linux-arm64";
    version = "1.547.0";
    src = fetchurl {
      url = "https://github.com/github/copilot-language-server-release/releases/download/1.547.0/copilot-language-server-linux-arm64-1.547.0.zip";
      sha256 = "sha256-7/dtkTzyeFwLBj3+AMTPtJ3++huNX5v6p8eayeLoJDk=";
    };
  };
  copilot-language-server-linux-x64 = {
    pname = "copilot-language-server-linux-x64";
    version = "1.547.0";
    src = fetchurl {
      url = "https://github.com/github/copilot-language-server-release/releases/download/1.547.0/copilot-language-server-linux-x64-1.547.0.zip";
      sha256 = "sha256-7wkEnfEChgXDSW97KtFUZk7xN2ojHqTRNFKG2WXLi2E=";
    };
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "6483be53397611b63259ce08a35108a47d4fc794";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "6483be53397611b63259ce08a35108a47d4fc794";
      fetchSubmodules = false;
      sha256 = "sha256-qqunTfZsgYEMiDnXaji6eyfBSbhmhFuAnh93UR7oimE=";
    };
    date = "2026-09-18";
  };
  gitlinker-nvim = {
    pname = "gitlinker-nvim";
    version = "5.5.0";
    src = fetchurl {
      url = "https://github.com/linrongbin16/gitlinker.nvim/archive/refs/tags/v5.5.0.tar.gz";
      sha256 = "sha256-UVCVLZT9VdgiwFSQFFIf7wEaMUZGsIJjikJpxjuL97g=";
    };
  };
  herdr-splits-nvim = {
    pname = "herdr-splits-nvim";
    version = "94f30cf4e9ac76ddf185a3acd0977be728fa4106";
    src = fetchFromGitHub {
      owner = "lmilojevicc";
      repo = "herdr-splits.nvim";
      rev = "94f30cf4e9ac76ddf185a3acd0977be728fa4106";
      fetchSubmodules = false;
      sha256 = "sha256-7rHAPSjd2n16FGOcqI/1KNHl1yCmMOVVwiJl/eEU9n8=";
    };
    date = "2026-08-17";
  };
  hlchunk-nvim = {
    pname = "hlchunk-nvim";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/shellRaining/hlchunk.nvim/archive/refs/tags/v1.3.0.tar.gz";
      sha256 = "sha256-eYwifigTRrXrW6xpFqLlqYFAftt64yweRGvvAvE7o5U=";
    };
  };
  kcl-language-server-darwin-amd64 = {
    pname = "kcl-language-server-darwin-amd64";
    version = "0.11.2";
    src = fetchurl {
      url = "https://github.com/kcl-lang/kcl/releases/download/v0.11.2/kclvm-v0.11.2-darwin-amd64.tar.gz";
      sha256 = "sha256-dvIxCVtpll1dUuPQVNkW+5vlNeHXFy+X/Ts/aKtYLFI=";
    };
  };
  kcl-language-server-darwin-arm64 = {
    pname = "kcl-language-server-darwin-arm64";
    version = "0.11.2";
    src = fetchurl {
      url = "https://github.com/kcl-lang/kcl/releases/download/v0.11.2/kclvm-v0.11.2-darwin-arm64.tar.gz";
      sha256 = "sha256-icMVp7KAoSzUTQ6BpRNYBSKfVvi/8EyQx227ix3bFCc=";
    };
  };
  noice-nvim = {
    pname = "noice-nvim";
    version = "4.10.0";
    src = fetchurl {
      url = "https://github.com/folke/noice.nvim/archive/refs/tags/v4.10.0.tar.gz";
      sha256 = "sha256-L9VGtlqsAezmi45ElHEmUFKCnrNQh8BA0ao9MJoyRr8=";
    };
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "2.11.0";
    src = fetchurl {
      url = "https://github.com/neovim/nvim-lspconfig/archive/refs/tags/v2.11.0.tar.gz";
      sha256 = "sha256-PcGmpUp/MFaEwAbF9tD5iWc/wsJG+7QMk+DhFPN19Xc=";
    };
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "2.31.0";
    src = fetchurl {
      url = "https://github.com/folke/snacks.nvim/archive/refs/tags/v2.31.0.tar.gz";
      sha256 = "sha256-TW5yI7AFU1AxNcZ2bzBMnH1txhGbClDvBGmsMg0wNJw=";
    };
  };
  ts-error-translator-nvim = {
    pname = "ts-error-translator-nvim";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v2.0.1.tar.gz";
      sha256 = "sha256-SSLrY2+0shDy/gvZeFmMGlLEZdtbMQT7XBS0WvF8X98=";
    };
  };
  vim-stylus = {
    pname = "vim-stylus";
    version = "99031823d216c4433fb5c2661a33a43fbebaff61";
    src = fetchFromGitHub {
      owner = "wavded";
      repo = "vim-stylus";
      rev = "99031823d216c4433fb5c2661a33a43fbebaff61";
      fetchSubmodules = false;
      sha256 = "sha256-tIVBNAAj78jJnoaejs850L+b4aTfp/UDFQQCxauAAcw=";
    };
    date = "2023-02-03";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "4164dee5b55da60f9fbd5c5e518323eb3d57c009";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "4164dee5b55da60f9fbd5c5e518323eb3d57c009";
      fetchSubmodules = false;
      sha256 = "sha256-DVqzJxN8iauM14sdd34KLisZ2Kgq0LhNgae9w9XCXHY=";
    };
    date = "2026-09-14";
  };
}
