name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    timeout-minutes: 15
    steps:
      - id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.SWAMPMAN_APP_ID }}
          private-key: ${{ secrets.SWAMPMAN_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            dotfiles
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: asa1984/ci-binary-cache-action@v1
        with:
          packages: .
      - name: Check flake.nix
        run: nix flake check
      - name: Build Neovim
        run: nix build
      - name: Run Neovim in headless mode
        run: nix run . -- --headless -c "q"
      - name: Create PR to asa1984/dotfiles
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh workflow run update-flake-input.yaml \
            --repo asa1984/dotfiles \
            --field input="asa1984-nvim" \
            --field title="chore(deps): update asa1984-nvim"
