name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-config: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake.nix
        run: nix flake check
      - name: Build Neovim
        run: nix build
      - name: Run Neovim in headless mode
        run: nix run . -- --headless -c "q"
